services: # Servisos serve para colocar os serviso para o user
  postgres: # O serviso
    image: bitnami/postgresql # Imagem do serviso/ o que ele tem que executar para fazer o serviso
    container_name: my_bot_for_discord # Nome do conteine no docker
    ports: # Numero da porta
      - 5432:5432
    environment: # Configuraçoes do postgres:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=users_for_bot
    volumes: # Onde vai fica o db
      - postgresql:/bitnami/postgresql
    networks: # Pra cominar tipo uma API
      - bot
networks:
  bot:
    driver: bridge
volumes:
  postgresql:
    name: users_for_bot
    driver: local